<?php

declare(strict_types=1);

namespace GoSuccess\TagLock\Service;

use RuntimeException;

use function file_exists;
use function plugin_dir_url;
use function rtrim;
use function wp_enqueue_script;
use function wp_enqueue_style;
use function wp_register_script;
use function wp_register_style;

/**
 * Asset Service
 *
 * Handles loading of JavaScript and CSS assets for admin and frontend.
 */
final class AssetService {

	public function __construct(
		private readonly LoggerService $logger
	) {}

	/**
	 * Load and validate the asset metadata array generated by @wordpress/scripts.
	 *
	 * @param string $assetFile Absolute path to the *.asset.php file.
	 * @return array{dependencies: array<int, string>, version: string}
	 */
	private function loadAssetMetadata( string $assetFile ): array {
		if ( ! file_exists( $assetFile ) ) {
			$this->logger->error( __( 'Missing asset metadata file', 'taglock' ), [ 'file' => $assetFile ] );
			throw new RuntimeException( "TagLock asset metadata file is missing: {$assetFile}" );
		}

		/** @var mixed $assetData */
		$assetData = require $assetFile;

		if (
			! is_array( $assetData ) ||
			! isset( $assetData['dependencies'], $assetData['version'] ) ||
			! is_array( $assetData['dependencies'] ) ||
			! is_string( $assetData['version'] )
		) {
			$this->logger->error( __( 'Invalid asset metadata format', 'taglock' ), [ 'file' => $assetFile ] );
			throw new RuntimeException( "TagLock asset metadata file is invalid: {$assetFile}" );
		}

		return $assetData;
	}

	/**
	 * Enqueue admin assets.
	 *
	 * @param string $hook The current admin page hook.
	 */
	public function enqueueAdminAssets( string $hook ): void {
		// Only load on TagLock settings page
		if ( 'settings_page_taglock-settings' !== $hook ) {
			return;
		}

		$pluginUrl = rtrim( plugin_dir_url( TAGLOCK_FILE ), '/' ) . '/';
		$pluginDir = dirname( TAGLOCK_FILE );

		// Load asset metadata generated by @wordpress/scripts
		$assetFile = "{$pluginDir}/assets/build/admin/index.asset.php";
		$assetData = $this->loadAssetMetadata( $assetFile );

		// Register admin script
		wp_register_script(
			'taglock-admin',
			"{$pluginUrl}assets/build/admin/index.js",
			$assetData['dependencies'],
			$assetData['version'],
			true
		);

		wp_enqueue_script( 'taglock-admin' );

		// Register admin styles
		wp_register_style(
			'taglock-admin',
			"{$pluginUrl}assets/build/admin/style-index.css",
			[],
			$assetData['version']
		);

		wp_enqueue_style( 'taglock-admin' );

		$this->logger->debug( __( 'Admin assets enqueued', 'taglock' ) );
	}

	/**
	 * Enqueue frontend assets.
	 *
	 * @param bool $force If true, enqueues even when hasShortcode() cannot detect it.
	 */
	public function enqueueFrontendAssets( bool $force = false ): void {
		// Only enqueue if shortcode is present (unless forced).
		if ( ! $force && ! $this->hasShortcode() ) {
			return;
		}

		$pluginUrl = rtrim( plugin_dir_url( TAGLOCK_FILE ), '/' ) . '/';
		$pluginDir = dirname( TAGLOCK_FILE );

		// Load asset metadata generated by @wordpress/scripts
		$assetFile = "{$pluginDir}/assets/build/frontend/index.asset.php";
		$assetData = $this->loadAssetMetadata( $assetFile );

		// Register frontend script
		wp_register_script(
			'taglock-frontend',
			"{$pluginUrl}assets/build/frontend/index.js",
			$assetData['dependencies'],
			$assetData['version'],
			true
		);

		wp_enqueue_script( 'taglock-frontend' );

		// Register frontend styles
		wp_register_style(
			'taglock-frontend',
			"{$pluginUrl}assets/build/frontend/style-index.css",
			[],
			$assetData['version']
		);

		wp_enqueue_style( 'taglock-frontend' );

		$this->logger->debug( __( 'Frontend assets enqueued', 'taglock' ) );
	}

	/**
	 * Check if the current post/page has the taglock shortcode.
	 *
	 * @return bool True if shortcode is present.
	 */
	private function hasShortcode(): bool {
		global $post;

		if ( ! $post ) {
			return false;
		}

		return has_shortcode( $post->post_content, 'taglock' );
	}

	/**
	 * Get the plugin version.
	 *
	 * @return string The plugin version.
	 */
	private function getPluginVersion(): string {
		if ( ! function_exists( 'get_plugin_data' ) ) {
			require_once ABSPATH . 'wp-admin/includes/plugin.php';
		}

		$pluginData = get_plugin_data( TAGLOCK_FILE );

		return $pluginData['Version'] ?? '1.0.0';
	}
}
